/* kpl925 service worker - generated by work/split_page.js - do not edit by hand */
  /* 9:25 鐪嬫澘 路 绂荤嚎鍏滃簳 Service Worker锛堢敱 work/split_page.js 鐢熸垚锛屼笉瑕佹墜鏀癸級 */ 
   var V = "kpl925-2026-10-08T10-41-30-446Z"; 
   var CORE = ["index.html", "kpl_data.js", "lhbdata.js", "gann-square-widget.js", "gann-nodes.js", "manifest.webmanifest", "favicon.ico", "apple-touch-icon.png", "icon-192.png"]; 
   self.addEventListener("install", function (e) { 
     self.skipWaiting(); 
     e.waitUntil(caches.open(V).then(function (c) { 
       return Promise.all(CORE.map(function (u) { return c.add(new Request(u, { cache: "reload" })).catch(function () {}); })); 
     })); 
   }); 
   self.addEventListener("activate", function (e) { 
     e.waitUntil(caches.keys().then(function (ks) { 
       return Promise.all(ks.filter(function (k) { return k !== V; }).map(function (k) { return caches.delete(k); })); 
     }).then(function () { return self.clients.claim(); })); 
   }); 
   function wt(p, ms) { 
     return new Promise(function (res, rej) { 
       var t = setTimeout(function () { rej(new Error("sw-timeout")); }, ms); 
       p.then(function (v) { clearTimeout(t); res(v); }, function (err) { clearTimeout(t); rej(err); }); 
     }); 
   } 
   self.addEventListener("fetch", function (e) { 
     var req = e.request; 
     if (req.method !== "GET") return; 
     var url; 
     try { url = new URL(req.url); } catch (err) { return; } 
     if (url.origin !== self.location.origin) return; 
     var isNav = req.mode === "navigate"; 
     e.respondWith(caches.open(V).then(function (cache) { 
       var key = isNav ? "index.html" : req; 
       var cachedP = cache.match(key, { ignoreSearch: true }); 
       return wt(fetch(req), 9000).then(function (fresh) { 
         if (fresh && fresh.ok) { try { cache.put(req, fresh.clone()); } catch (err2) {} } 
         return fresh; 
       }).catch(function (err3) { 
         return cachedP.then(function (c) { if (c) return c; throw err3; }); 
       }); 
     })); 
   }); 
 